### ISSUE TITLE
double_gauss example

### ISSUE THREAD

**Issue by robmarkcole** [jordens/rayopt#13]
Getting 'material None/None/sk4 not found'

**Comment by jordens** [comment]
works fine here, please provide context as in #14

**Comment by robmarkcole** [comment]
Hi, its a fresh install of py35_103, tested on both Mac and PC with same error. Looks like I need to link to a material library somewhere.

s = system_from_text(text, columns.split(),
    description="four element double gauss, intermediate optical design")

KeyError                                  Traceback (most recent call last)
<ipython-input-4-2ec04651622a> in <module>()
      1 s = system_from_text(text, columns.split(),
----> 2     description="four element double gauss, intermediate optical design")

C:\Users\RCole02.ROYALSURREY\AppData\Local\Continuum\Anaconda3\lib\site-packages\rayopt\formats.py in system_from_text(text, *args, **kwargs)
     83     n = max(len(l) for l in array)
     84     array = [l for l in array if len(l) == n]
---> 85     return system_from_array(array, *args, **kwargs)
     86 
     87 

C:\Users\RCole02.ROYALSURREY\AppData\Local\Continuum\Anaconda3\lib\site-packages\rayopt\formats.py in system_from_array(data, columns, shifts, material_map, **kwargs)
     74             mat = try_get(line, columns, "material")
     75             mat = material_map.get(mat, mat)
---> 76             m = Material.make(mat)
     77             el.material = m
     78     return s

C:\Users\RCole02.ROYALSURREY\AppData\Local\Continuum\Anaconda3\lib\site-packages\rayopt\material.py in make(cls, name)
    116         from .library import Library
    117         lib = Library.one()
--> 118         return lib.get("material", name, catalog, source)
    119 
    120     def __str__(self):

C:\Users\RCole02.ROYALSURREY\AppData\Local\Continuum\Anaconda3\lib\site-packages\rayopt\library.py in get(self, *args, **kwargs)
    118 
    119     def get(self, *args, **kwargs):
--> 120         for k in self.get_all(*args, **kwargs):
    121             return k
    122 

C:\Users\RCole02.ROYALSURREY\AppData\Local\Continuum\Anaconda3\lib\site-packages\rayopt\library.py in get_all(self, typ, name, catalog, source, **kwargs)
    133         if not res.count():
    134             raise KeyError("{} {}/{}/{} not found".format(
--> 135                 typ, source, catalog, name))
    136         for item in res:
    137             yield item.parse()

KeyError: 'material None/None/sk4 not found'

**Comment by robmarkcole** [comment]
OK so probably I need to do this

get and install http://www.lambdares.com/images/OSLO/OSLO662_EDU_Installer.exe
get and install http://downloads.radiantsourcemodels.com/Downloads/Zemax_2015-03-03_x32.exe

**Comment by jordens** [comment]
yes.
