### ISSUE TITLE
elphel_v2

### ISSUE THREAD

**Issue by robmarkcole** [jordens/rayopt#14]
ValueError: ('no viable interval found', 0.0, 9.313225746154785e-10, nan)

**Comment by jordens** [comment]
works fine here. please provide some context. which rayopt version, which rayopt-notebooks version, what exactly are you doing, what do you expect, what exactly is the complete error message.

**Comment by jordens** [comment]
@robmarkcole ping

**Comment by robmarkcole** [comment]
My apologies, version py35_103, attempting to run the example, my notebook is here 

https://github.com/robmarkcole/Useful-python-for-medical-physics/blob/master/Experiments%20in%20ipython%20notebooks/Ray-opt/Examples/elphel_v2%20RC_27_1_17.ipynb

**Comment by jordens** [comment]
You need the materials. Either get them from Oslo/Zemax: the current versions may work just as well. Or define them yourself.
