### ISSUE TITLE
Diffractive, periodic or parallel optical elements?

### ISSUE THREAD

**Issue by MaximilianHoffmann** [jordens/rayopt#2]
Hi ,

thanks for this great package. I have one questions: Do you see any way to trace rays through a periodic structure like a DMD, SLM or any kind of grating ? Additionally, I had problems setting even two macro mirror side by side with help of offset and angle, which reflect part of the light in different directions.

Thanks
Max

**Comment by jordens** [comment]
Gratings would be implemented along the usual lines (e.g. G. H. Spencer and M. V. R. K. Murty, General Ray-Tracing Procedure, JOSA, Vol. 52, Issue 6, pp. 672-676 (1962) doi:10.1364/JOSA.52.000672). For DMD/SLM you would probably implement it yourself depending on what effects you want to include. There are also well know algorithms in the literature for e.g. GRIN lenses. All you need to do is implement something that follows the `rayopt.elements.Element.propagate()` interface.

**Comment by MaximilianHoffmann** [comment]
Thanks a lot,  I will look into this function, and try to implement, what I need.
