### ISSUE TITLE
pip install error

### ISSUE THREAD

**Issue by haynesyy** [jordens/rayopt#20]
trying to install rayopt via pip on Windows, with Python 3.6.

keep coming up with this error:
ValueError: 'rayopt/simplex_accel.pyx' doesn't match any files

Any tips?

**Comment by himbeles** [comment]
Same issue here with macOS 10.13 and Python 3.6.3

**Comment by jordens** [comment]
Please supply context: Python distribution, what command are you actually running, what is the actual output, what packages do you have installed.

**Comment by jordens** [comment]
I can't reproduce it here with Python 3.6 on Linux, Conda, Cython 0.26.

**Comment by jordens** [comment]
I'll have to guess. You tried to install it via PyPi (the README does not not mention that option at all). That didn't work because those tarballs were broken.

**Comment by himbeles** [comment]
Sorry for the incomplete information. 
I tried to install via pip: pip3 install rayopt

Python install was done using homebrew on the Mac (no conda). 
Python 0.27.1

**Comment by jordens** [comment]
This should be fixed now. But generally, doing `pip install -e git+https://github.com/jordens/rayopt.git#egg=rayopt` or using conda is better.

**Comment by jordens** [comment]
And there is no Python 0.27.1 ;)

**Comment by haynesyy** [comment]
Sorry mate, it's at home, I am at work at the moment. Will give your suggestions a go this evening and give you a buzz back with context if it still doesn't work.

**Comment by haynesyy** [comment]
OK. I have installed Anaconda, to try going that route... this is my cmd:

(C:\Users\tom\Anaconda3) C:\Users\tom\Documents>conda install -c https://conda.anaconda.org/jordens/channel/ci rayopt
Fetching package metadata ...............
Solving package specifications: .

UnsatisfiableError: The following specifications were found to be in conflict:
  - python 3.6*
  - rayopt -> python 3.5*

confused.com...!

**Comment by haynesyy** [comment]
You know what, don't even worry about it. I did a pip install on my other machine and it worked fine.... i'm going away now....

**Comment by jordens** [comment]
As I said above, I fixed the PyPi source package. The Conda packages need to depend on a specific Python version.

**Comment by himbeles** [comment]
Sorry, I meant Cython 0.27.1

**Comment by himbeles** [comment]
Installing the egg from git works! Thanks!
