### ISSUE TITLE
unnecessary condition in paraxial trace?

### ISSUE THREAD

**Issue by MaximilianHoffmann** [jordens/rayopt#4]
https://github.com/jordens/rayopt/blob/master/rayopt/paraxial_trace.py#L62-L63

When would this condition hold, especially  `n[0].shape==n` ?
Because one line before n is set to `n=self.length`

Thanks
Max

**Comment by jordens** [comment]
What is the issue here?

You can reuse a `ParaxialTrace` (change its `System` and then `.update()`):
Compare the two cases:
```python
s = System(...)
p = ParaxialTrace(s)
if A:
    s.append(Spheroid(...))
else:
    s[-1].distance += 1
p.update()
```

**Comment by MaximilianHoffmann** [comment]
I see, then this makes a lot of sense. Thank you
