### ISSUE TITLE
Question: Why is paraxial free space propagation divided by refractive index?

### ISSUE THREAD

**Issue by MaximilianHoffmann** [jordens/rayopt#6]
```
def paraxial_matrix(self, n0, l):
        m = np.eye(4)
        # 4x4 block matrix, M = [[A, B], [C, D]], A is 2x2 tan sag
        d = self.distance
```
then:
```
        m[0, 2] = m[1, 3] = d/n0
        return n0, m
```

Isn't the normal propagation matrix only dependent on the distance?

Thanks
Max

**Comment by MaximilianHoffmann** [comment]
Slope definition like Siegmann Lasers p. 584 , e.g. relative slope

**Comment by jordens** [comment]
You can write it either way. It is just fewer arguments and less code. If you use the geometric distance here you have to mess with a lot more things though.

And Siegmann. Yes.
